
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdghqamfuelhedikkwpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZ2hxYW1mdWVsaGVkaWtrd3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDc1MzEsImV4cCI6MjA1NzY4MzUzMX0.RX-yWDWjZ-Kzmcu4tCP5MFKucuIkqljIInhtVXaTJfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
